version: '3.8'
services:
  eureka-server:
    container_name: eureka-service
    build: ./eureka-server
    ports:
      - "8761:8761"
  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    env_file:
      - ./api-gateway/src/main/resources/application.properties
    links:
      - eureka-server
    depends_on:
      - eureka-server
    ports:
      - "8080:8080"
  account-service:
    container_name: account-service
    build: ./account-service
    ports:
      - "8763:8763"
    depends_on:
      - PostgreSQL
      - eureka-server
    links:
      - PostgreSQL
      - eureka-server
    env_file:
      - ./account-service/src/main/resources/application.properties
  customer-service:
    container_name: customer-service
    build: ./customer-service
    ports:
      - "8762:8762"
    depends_on:
      - PostgreSQL
      - eureka-server
    links:
      - PostgreSQL
      - eureka-server
    env_file:
      - ./customer-service/src/main/resources/application.properties
  transaction-service:
    container_name: transaction-service
    build: ./transaction-service
    ports:
      - "8764:8764"
    depends_on:
      - PostgreSQL
      - eureka-server
    links:
      - PostgreSQL
      - eureka-server
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: weg
    env_file:
      - ./transaction-service/src/main/resources/application.properties
  PostgreSQL:
    container_name: PostgreSQL
    restart: always
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=sent1234
      - POSTGRES_USER=postgres